drop table if exists building CASCADE;

create table building
(
    id            bigint generated by default as identity,
    price         bigint not null,
    square_meters bigint not null,
    primary key (id)
);