drop table if exists person CASCADE;

create table person
(
    id           bigint generated by default as identity,
    address      varchar(255),
    firstname    varchar(255),
    phone_number varchar(255),
    surname      varchar(255),
    primary key (id)
);