/*DROP TYPE IF EXISTS room_type_enum CASCADE;
CREATE TYPE room_type_enum AS ENUM ('BALCONY', 'BATHROOM', 'BEDROOM', 'DINING_ROOM', 'GARAGE', 'GUEST_ROOM',
    'HALLWAY', 'KITCHEN', 'LIVING_ROOM', 'OFFICE', 'UTILITY_ROOM', 'WARDROBE');
*/
drop table if exists room CASCADE;

create table room
(
    id        bigint generated by default as identity,
    room_type integer not null,
    size      bigint  not null check (size >=1),
    building bigint,
    primary key (id)
);

alter table room
    add constraint Fk_rooms_building foreign key (building) references building;